cosy:
  engine:
    kubernetes:
      kubeconfig: "C:/path/to/.kube/config"
    docker:
      socket-path: "npipe:////./pipe/docker_engine" # example windows path
      # api-version: "1.41" # Optional: API version
