server:
  servlet:
    context-path: /api
spring:
  application:
    name: cosy-backend
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:postgresql://localhost:5432/cosy
    username: cosy
    password: cosy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
jwt:
  secret-key: ${COSY_JWT_SECRET_KEY:e8996bf24977ce5615015c717447911799207025d1998a01256b7b7717bac18e} #change in prod
  identity-token-expiration-time: 3600000 #1 hour
  refresh-token-expiration-time: 2678400000 #1 month
management:
  endpoints:
    web:
      exposure:
        include: "health,readiness,liveness"

cosy:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - https://cosy.jannekeipert.de
      - https://cosy-docker.pybay.de
  games-api:
    url: https://cosy-game-api.jannekeipert.de
  templates-api:
    url: https://cosy-templates.jannekeipert.de/templates
  custom-metrics:
    base-url: http://host.docker.internal:8080
    period-seconds: 2
  loki:
    username: ${COSY_LOKI_USER:loki-user}
    password: ${COSY_LOKI_PASSWORD:loki-password}
    url: http://localhost:3100
    application-name: cosy-backend # Label to identify logs from this application
  influx:
    url: http://localhost:8086
    token: ${COSY_INFLUX_TOKEN:cosy-admin-token}
    org: cosy-org
    bucket: cosy-bucket
  engine:
    # Docker-specific configuration
    docker:
      socket-path: ${COSY_DOCKER_SOCKET_PATH:unix:///var/run/docker.sock} # Docker socket
      tls: false # Whether to use TLS
      cert-path: "" # Path to TLS certs if enabled
      volume-directory: ${COSY_DOCKER_VOLUME_DIRECTORY:./dummy/cosy/volume-mounts}
      container-name-prefix: ${COSY_DOCKER_CONTAINER_PREFIX:cosy-} # Prefix for container names
      in-backend-volume-mount-path: ${COSY_DOCKER_BACKEND_VOLUME_MOUNT_PATH:./dummy/cosy/volume-mounts}
  footer:
    full-name: ${COSY_FOOTER_FULL_NAME:Full Name}
    email: ${COSY_FOOTER_EMAIL:yourEmail@example.org}
    phone: ${COSY_FOOTER_PHONE:+49 123 4567890}
    street: ${COSY_FOOTER_STREET:Street 5}
    city: ${COSY_FOOTER_CITY:12345 City}
  defaults:
    owner:
      username: admin
      password: admin
