package com.magentamause.cosybackend;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

/**
 * Exercises the risky <em>upgrade</em> path that every self-hosted Cosy instance takes on its first
 * boot after Flyway is adopted, and proves it converges on the same schema a fresh install gets.
 *
 * <p>Cosy is self-hosted: each operator ran their own instance whose schema was grown incrementally
 * by {@code ddl-auto: update}. When they upgrade to the first Flyway release, Flyway finds a
 * non-empty schema, stamps it as V1 via {@code baseline-on-migrate}, then applies V2+ and hands the
 * result to Hibernate {@code validate}. {@link FlywayMigrationTest} only covers the fresh-DB path
 * (empty → V1+V2); this test covers the upgrade path end to end.
 *
 * <p>The heart of the test is a schema diff, not the {@code validate} step. Hibernate {@code
 * validate} <em>strips length arguments</em> when it compares column types, so it treats {@code
 * varchar(255)} and {@code text} as the same type and would never have flagged the original
 * truncation bug. To catch length/nullability/type drift that {@code validate} is blind to, we
 * compare {@code information_schema.columns} between the upgraded legacy database and a freshly
 * migrated one and assert they are identical.
 *
 * <p><strong>Caveat:</strong> the "legacy" database here is generated by {@code ddl-auto: update}
 * from the <em>current</em> entities and then seeded with representative <em>feature-branch
 * orphans</em> (tables and columns a never-merged branch's {@code ddl-auto} would have created), so
 * it approximates — but does not perfectly reproduce — a schema that was grown across many
 * historical entity versions. It is the closest reproducible stand-in available in CI. Seeding the
 * orphans closes the gap the reviewer pointed out: without them the legacy DB was synthesized
 * purely from current entities and could never exercise the V3 cleanup.
 *
 * <p>Gated behind {@code CI_PG_TESTS=true} so it never runs on a developer machine by accident. It
 * is a plain JUnit class (not {@code @SpringBootTest}) because it needs to manage several Spring
 * contexts and raw JDBC connections against multiple scratch databases within one test.
 */
@EnabledIfEnvironmentVariable(named = "CI_PG_TESTS", matches = "true")
class FlywayUpgradePathTest {

    // The ci Postgres server, matching src/test/resources/application-ci-pg.yaml.
    private static final String HOST = "localhost";
    private static final int PORT = 5432;
    private static final String USER = "cosy";
    private static final String PASSWORD = "cosy";

    // Admin database used to create/drop the scratch databases below.
    private static final String ADMIN_DB = "cosy_ci";
    private static final String LEGACY_DB = "cosy_ci_legacy";
    private static final String FRESH_DB = "cosy_ci_fresh";

    private static String jdbcUrl(String database) {
        return "jdbc:postgresql://" + HOST + ":" + PORT + "/" + database;
    }

    @BeforeAll
    static void createScratchDatabases() throws SQLException {
        try (Connection admin = DriverManager.getConnection(jdbcUrl(ADMIN_DB), USER, PASSWORD);
                Statement statement = admin.createStatement()) {
            for (String database : List.of(LEGACY_DB, FRESH_DB)) {
                // WITH (FORCE) terminates any leftover sessions from a previous aborted run.
                statement.execute("DROP DATABASE IF EXISTS " + database + " WITH (FORCE)");
                statement.execute("CREATE DATABASE " + database);
            }
        }
    }

    @AfterAll
    static void dropScratchDatabases() {
        // Best effort: never fail the build because cleanup could not run.
        try (Connection admin = DriverManager.getConnection(jdbcUrl(ADMIN_DB), USER, PASSWORD);
                Statement statement = admin.createStatement()) {
            for (String database : List.of(LEGACY_DB, FRESH_DB)) {
                statement.execute("DROP DATABASE IF EXISTS " + database + " WITH (FORCE)");
            }
        } catch (SQLException ignored) {
            // Leftover scratch databases are harmless; the next run recreates them.
        }
    }

    @Test
    void upgradePathConvergesOnFreshSchema() throws SQLException {
        // (b) Simulate a pre-Flyway deployment: let Hibernate ddl-auto=update build the schema on
        // cosy_ci_legacy from the current entities, with Flyway switched off. This is the state an
        // existing self-hosted instance is in just before it upgrades.
        bootApp(
                "spring.datasource.url=" + jdbcUrl(LEGACY_DB),
                "spring.flyway.enabled=false",
                "spring.jpa.hibernate.ddl-auto=update");

        // (b2) Seed feature-branch leftovers: entities from a never-merged mc-router branch that
        // ddl-auto=update would have materialised on any DB that ran it. These are exactly the
        // orphans V3 drops. The fresh reference DB (step d) never has them, so the schema diff in
        // step (e) fails unless V3 removes every one of them from the upgraded legacy DB. The FK on
        // mc_router_domains -> cosy_instance_settings_entity proves V3's child-before-parent drop
        // order is correct.
        try (Connection legacy = DriverManager.getConnection(jdbcUrl(LEGACY_DB), USER, PASSWORD);
                Statement statement = legacy.createStatement()) {
            statement.execute(
                    "CREATE TABLE cosy_instance_settings_entity ("
                            + " id bigint primary key,"
                            + " mc_router_enabled boolean,"
                            + " mc_router_port integer)");
            statement.execute(
                    "CREATE TABLE mc_router_domains ("
                            + " cosy_instance_settings_id bigint not null"
                            + " references cosy_instance_settings_entity(id),"
                            + " domain varchar(255))");
            statement.execute(
                    "CREATE TABLE user_allowed_ports ("
                            + " user_uuid varchar(255) not null,"
                            + " port_range varchar(255))");
            statement.execute(
                    "ALTER TABLE user_entity"
                            + " ADD COLUMN allow_game_server_creation boolean DEFAULT true");
        }

        // (c) Upgrade it: boot again with Flyway enabled (baseline-on-migrate from the ci-pg
        // profile / application.yaml defaults) and ddl-auto=validate. This is the exact path every
        // self-hosted instance takes on its first boot after this release.
        bootApp(
                "spring.datasource.url=" + jdbcUrl(LEGACY_DB),
                "spring.jpa.hibernate.ddl-auto=validate");

        // Flyway should have baselined the existing schema at V1 and then applied V2, with nothing
        // failing. (If validate had rejected the migrated schema the boot above would have thrown.)
        try (Connection legacy = DriverManager.getConnection(jdbcUrl(LEGACY_DB), USER, PASSWORD)) {
            assertThat(
                            count(
                                    legacy,
                                    "SELECT count(*) FROM flyway_schema_history WHERE"
                                            + " version = '1' AND type = 'BASELINE'"))
                    .as("baseline row for V1")
                    .isEqualTo(1);
            assertThat(
                            count(
                                    legacy,
                                    "SELECT count(*) FROM flyway_schema_history WHERE"
                                            + " version = '2' AND success = true"))
                    .as("applied V2 migration")
                    .isEqualTo(1);
            assertThat(
                            count(
                                    legacy,
                                    "SELECT count(*) FROM flyway_schema_history WHERE"
                                            + " version = '3' AND success = true"))
                    .as("applied V3 cleanup migration")
                    .isEqualTo(1);
            assertThat(
                            count(
                                    legacy,
                                    "SELECT count(*) FROM flyway_schema_history WHERE"
                                            + " success = false"))
                    .as("no failed migrations")
                    .isZero();
        }

        // (d) Fresh reference: run the migrations from scratch on an empty database using plain
        // Flyway — no Spring context needed. This is the schema a brand-new install receives.
        Flyway.configure()
                .dataSource(jdbcUrl(FRESH_DB), USER, PASSWORD)
                .locations("classpath:db/migration")
                .load()
                .migrate();

        // (e) The real drift guard: the upgraded legacy schema must be byte-for-byte identical to
        // the freshly migrated schema. This catches length/nullability/type drift that Hibernate
        // validate cannot see because it strips length args when comparing column types.
        List<ColumnInfo> legacyColumns;
        List<ColumnInfo> freshColumns;
        try (Connection legacy = DriverManager.getConnection(jdbcUrl(LEGACY_DB), USER, PASSWORD);
                Connection fresh = DriverManager.getConnection(jdbcUrl(FRESH_DB), USER, PASSWORD)) {
            legacyColumns = readPublicColumns(legacy);
            freshColumns = readPublicColumns(fresh);
        }

        assertThat(legacyColumns)
                .as(
                        "columns of the upgraded (baseline V1 + V2) schema must equal the columns of"
                                + " a fresh V1+V2 migration")
                .containsExactlyElementsOf(freshColumns);
    }

    /**
     * Boots the full application with the {@code ci-pg} profile and the given property overrides.
     */
    private static void bootApp(String... properties) {
        // Full servlet boot on a random port (faithful to a real instance start). A random port
        // avoids conflicts when the contexts boot sequentially; web-application-type=none can't be
        // used here because the security layer's CorsConfigurationSource comes from the web MVC
        // layer and is absent without a web context.
        String[] withDefaults = new String[properties.length + 1];
        withDefaults[0] = "server.port=0";
        System.arraycopy(properties, 0, withDefaults, 1, properties.length);

        // Pass overrides as command-line args ("--key=value"), NOT via .properties(): the latter
        // registers them as DEFAULT properties (lowest precedence), so the active ci-pg profile
        // yaml and application.yaml would win and silently point the boot back at cosy_ci with
        // ddl-auto=validate. Command-line args have near-highest precedence and beat every config
        // file, which is exactly what we need to redirect the datasource to the scratch database.
        // Do NOT revert this to .properties().
        String[] args = new String[withDefaults.length];
        for (int i = 0; i < withDefaults.length; i++) {
            args[i] = "--" + withDefaults[i];
        }

        try (ConfigurableApplicationContext ignored =
                new SpringApplicationBuilder(CosyBackendApplication.class)
                        .profiles("ci-pg")
                        .run(args)) {
            // Booting (and cleanly shutting down) is the assertion; the schema effects persist in
            // the database and are checked afterwards.
        }
    }

    /**
     * Reads {@code information_schema.columns} for the {@code public} schema, excluding Flyway's
     * own bookkeeping table, as a sorted list so two databases can be compared for equality.
     */
    private static List<ColumnInfo> readPublicColumns(Connection connection) throws SQLException {
        List<ColumnInfo> columns = new ArrayList<>();
        // column_default is included because Hibernate validate does not check column defaults and
        // neither did this diff before: a migration that omitted a DEFAULT (e.g. user_entity
        // .can_create_game_servers boolean DEFAULT true) would otherwise drift past both checks --
        // a real behaviour change for anything inserting rows outside JPA.
        String sql =
                "SELECT table_name, column_name, data_type, character_maximum_length,"
                        + " numeric_precision, is_nullable, column_default"
                        + " FROM information_schema.columns"
                        + " WHERE table_schema = 'public'"
                        + " AND table_name <> 'flyway_schema_history'";
        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql)) {
            while (rs.next()) {
                columns.add(
                        new ColumnInfo(
                                rs.getString("table_name"),
                                rs.getString("column_name"),
                                rs.getString("data_type"),
                                (Integer) rs.getObject("character_maximum_length"),
                                (Integer) rs.getObject("numeric_precision"),
                                rs.getString("is_nullable"),
                                rs.getString("column_default")));
            }
        }
        columns.sort(
                Comparator.comparing(ColumnInfo::tableName).thenComparing(ColumnInfo::columnName));
        return columns;
    }

    private static int count(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql)) {
            rs.next();
            return rs.getInt(1);
        }
    }

    /**
     * One row of {@code information_schema.columns}. Being a record, its {@code equals}/{@code
     * toString} give a readable per-field diff when two schemas disagree.
     */
    private record ColumnInfo(
            String tableName,
            String columnName,
            String dataType,
            Integer characterMaximumLength,
            Integer numericPrecision,
            String isNullable,
            String columnDefault) {}
}
