services:
  cosy-dev-postgres:
    image: postgres:16-alpine
    container_name: cosy-dev-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cosy
      - POSTGRES_USER=cosy
      - POSTGRES_PASSWORD=cosy
    volumes:
      - cosy-dev-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cosy"]
      interval: 10s
      timeout: 5s
      retries: 5
  cosy-dev-loki:
    image: grafana/loki:2.9.4
    container_name: cosy-dev-loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - cosy-dev-loki-data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
    expose:
      - "3100"
  cosy-dev-nginx:
    image: nginx:1.25
    container_name: cosy-dev-loki-nginx
    ports:
      - "3100:80"
    volumes:
      - ./loki-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - cosy-dev-loki
  cosy-dev-influx:
    image: influxdb:2.7-alpine
    container_name: cosy-dev-influx
    ports:
    - "8086:8086"
    volumes:
      - cosy-dev-influx-data:/var/lib/influxdb2
      - cosy-dev-influx-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: cosy
      DOCKER_INFLUXDB_INIT_PASSWORD: cosy-password
      DOCKER_INFLUXDB_INIT_ORG: cosy-org
      DOCKER_INFLUXDB_INIT_BUCKET: cosy-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: cosy-admin-token
volumes:
  cosy-dev-influx-data:
  cosy-dev-influx-config:
  cosy-dev-postgres-data:
  cosy-dev-loki-data:
