-- Baseline of the pre-Flyway schema.
--
-- This snapshot reproduces the schema that Hibernate `ddl-auto: update` created before
-- Flyway was adopted. It only runs on fresh/empty databases: existing deployments are
-- baselined at version 1 (spring.flyway.baseline-on-migrate + baseline-version=1), so
-- Flyway records V1 as already applied for them and starts real migrations at V2.
--
-- NOTE: `template_entity.description` is intentionally kept as varchar(255) here exactly
-- as it existed pre-Flyway. V2 widens it to text, so both fresh and existing databases
-- converge on the same final state.

CREATE TABLE public.access_group_users (
    access_group_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

CREATE TABLE public.cosy_instance_settings_entity (
    id bigint NOT NULL,
    mc_router_enabled boolean,
    mc_router_port integer
);

ALTER TABLE public.cosy_instance_settings_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cosy_instance_settings_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.docker_execution_command (
    game_server_configuration_uuid character varying(255) NOT NULL,
    command_part character varying(255)
);

CREATE TABLE public.dummy_instantiated_entity (
    value_key character varying(255) NOT NULL
);

CREATE TABLE public.environment_variables (
    game_server_configuration_uuid character varying(255) NOT NULL,
    env_key character varying(255),
    env_value character varying(255)
);

CREATE TABLE public.footer_entity (
    id bigint NOT NULL,
    city character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    street character varying(255) NOT NULL
);

ALTER TABLE public.footer_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.footer_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.game_entity (
    uuid character varying(255) NOT NULL,
    external_game_id integer NOT NULL,
    hero_url character varying(255),
    logo_url character varying(255),
    name character varying(255) NOT NULL,
    slug character varying(255)
);

CREATE TABLE public.game_server_access_group_entity (
    uuid character varying(255) NOT NULL,
    group_name character varying(255),
    game_server_id character varying(255)
);

CREATE TABLE public.game_server_access_group_entity_permissions (
    game_server_access_group_entity_uuid character varying(255) NOT NULL,
    permissions character varying(255),
    CONSTRAINT game_server_access_group_entity_permissions_permissions_check CHECK (((permissions)::text = ANY ((ARRAY['ADMIN'::character varying, 'SEE_SERVER'::character varying, 'START_STOP_SERVER'::character varying, 'READ_SERVER_LOGS'::character varying, 'READ_SERVER_METRICS'::character varying, 'READ_SERVER_PRIVATE_DASHBOARD'::character varying, 'SEND_COMMANDS'::character varying, 'READ_SERVER_SERVER_FILES'::character varying, 'CHANGE_SERVER_FILES'::character varying, 'CHANGE_SERVER_CONFIGS'::character varying, 'CHANGE_METRICS_SETTINGS'::character varying, 'CHANGE_PRIVATE_DASHBOARD_SETTINGS'::character varying, 'CHANGE_PUBLIC_DASHBOARD_SETTINGS'::character varying, 'CHANGE_PERMISSIONS_SETTINGS'::character varying, 'CHANGE_RCON_SETTINGS'::character varying, 'CHANGE_WEBHOOK_SETTINGS'::character varying, 'TRANSFER_SERVER_OWNERSHIP'::character varying, 'DELETE_SERVER'::character varying])::text[])))
);

CREATE TABLE public.game_server_annotations (
    game_server_configuration_uuid character varying(255) NOT NULL,
    annotation_value character varying(255),
    annotation_key character varying(255) NOT NULL
);

CREATE TABLE public.game_server_entity (
    uuid character varying(255) NOT NULL,
    container_secret character varying(255),
    created_on timestamp(6) without time zone,
    custom_metric_holder json,
    design character varying(255),
    docker_max_cpu_cores real,
    docker_memory_limit character varying(255),
    docker_image_name character varying(255) NOT NULL,
    docker_image_tag character varying(255),
    enabled boolean,
    password character varying(255),
    port integer,
    server_name character varying(255),
    status character varying(255),
    timestamp_last_started timestamp(6) without time zone,
    game_uuid character varying(255),
    owner_uuid character varying(255),
    public_dashboard_uuid character varying(255),
    CONSTRAINT game_server_entity_design_check CHECK (((design)::text = ANY ((ARRAY['HOUSE'::character varying, 'CASTLE'::character varying])::text[]))),
    CONSTRAINT game_server_entity_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'STOPPED'::character varying, 'FAILED'::character varying, 'PULLING_IMAGE'::character varying, 'AWAITING_UPDATE'::character varying, 'STOPPING'::character varying])::text[])))
);

CREATE TABLE public.game_server_webhook_events (
    webhook_id character varying(255) NOT NULL,
    event_type character varying(255),
    CONSTRAINT game_server_webhook_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['SERVER_STARTED'::character varying, 'SERVER_STOPPED'::character varying, 'SERVER_FAILED'::character varying])::text[])))
);

CREATE TABLE public.host_volume_mount_configuration (
    uuid character varying(255) NOT NULL,
    container_path character varying(255) NOT NULL,
    host_path character varying(255) NOT NULL,
    read_only boolean NOT NULL,
    game_server_configuration_host_uuid character varying(255)
);

CREATE TABLE public.layout (
    uuid character varying(255) NOT NULL,
    size character varying(255) NOT NULL,
    CONSTRAINT layout_size_check CHECK (((size)::text = ANY ((ARRAY['SMALL'::character varying, 'MEDIUM'::character varying, 'LARGE'::character varying])::text[])))
);

CREATE TABLE public.mc_router_domains (
    cosy_instance_settings_id bigint NOT NULL,
    domain character varying(255)
);

CREATE TABLE public.mc_router_server_domains (
    game_server_uuid character varying(255) NOT NULL,
    domain character varying(255)
);

CREATE TABLE public.metric_layout (
    metric_type character varying(255) NOT NULL,
    uuid character varying(255) NOT NULL,
    metric_layout_uuid character varying(255),
    metric_layout_index integer
);

CREATE TABLE public.port_mappings (
    game_server_configuration_uuid character varying(255) NOT NULL,
    container_port integer,
    instance_port integer,
    protocol character varying(255),
    CONSTRAINT port_mappings_protocol_check CHECK (((protocol)::text = ANY ((ARRAY['TCP'::character varying, 'UDP'::character varying])::text[])))
);

CREATE TABLE public.private_dashboard_content (
    private_dashboard_layout_id character varying(255) NOT NULL,
    key character varying(255),
    value character varying(255)
);

CREATE TABLE public.private_dashboard_layout (
    layout_type character varying(255) NOT NULL,
    metric_type character varying(255),
    title character varying(255),
    uuid character varying(255) NOT NULL,
    private_dashboard_layout_uuid character varying(255),
    private_dashboard_layout_index integer,
    CONSTRAINT private_dashboard_layout_layout_type_check CHECK (((layout_type)::text = ANY ((ARRAY['METRIC'::character varying, 'LOGS'::character varying, 'FREETEXT'::character varying])::text[])))
);

CREATE TABLE public.public_dashboard (
    uuid character varying(255) NOT NULL,
    enabled boolean NOT NULL
);

CREATE TABLE public.public_dashboard_content (
    public_dashboard_layout_id character varying(255) NOT NULL,
    key character varying(255),
    value character varying(255)
);

CREATE TABLE public.public_dashboard_layout (
    layout_type character varying(255) NOT NULL,
    metric_type character varying(255),
    title character varying(255),
    uuid character varying(255) NOT NULL,
    public_dashboard_uuid character varying(255),
    public_dashboard_layout_index integer,
    CONSTRAINT public_dashboard_layout_layout_type_check CHECK (((layout_type)::text = ANY ((ARRAY['METRIC'::character varying, 'LOGS'::character varying, 'FREETEXT'::character varying])::text[])))
);

CREATE TABLE public.template_entity (
    uuid character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    docker_execution_command jsonb,
    docker_image_name character varying(255) NOT NULL,
    docker_image_tag character varying(255) NOT NULL,
    environment_variables jsonb,
    file_mounts jsonb,
    game_id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    path character varying(255) NOT NULL,
    port_mappings jsonb,
    resource_limit jsonb,
    variables jsonb,
    annotations jsonb,
    host_mounts jsonb,
    tags jsonb
);

CREATE TABLE public.user_allowed_ports (
    user_uuid character varying(255) NOT NULL,
    port_range character varying(255)
);

CREATE TABLE public.user_entity (
    uuid character varying(255) NOT NULL,
    allow_game_server_creation boolean DEFAULT true,
    default_password_reset boolean NOT NULL,
    docker_max_cpu_cores real,
    docker_memory_limit character varying(255),
    mc_router_allow_all_domains boolean DEFAULT false,
    password character varying(255) NOT NULL,
    port_restrictions_enabled boolean DEFAULT true,
    role character varying(255),
    username character varying(255) NOT NULL,
    can_create_game_servers boolean DEFAULT true NOT NULL,
    CONSTRAINT user_entity_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'QUOTA_USER'::character varying])::text[])))
);

CREATE TABLE public.user_invite_allowed_ports (
    user_invite_uuid character varying(255) NOT NULL,
    port_range character varying(255)
);

CREATE TABLE public.user_invite_entity (
    uuid character varying(255) NOT NULL,
    allow_game_server_creation boolean DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    docker_max_cpu_cores real,
    docker_memory_limit character varying(255),
    mc_router_allow_all_domains boolean DEFAULT false,
    port_restrictions_enabled boolean DEFAULT true,
    role character varying(255),
    secret_key character varying(255) NOT NULL,
    username character varying(255),
    invited_by_id character varying(255),
    can_create_game_servers boolean DEFAULT true NOT NULL,
    CONSTRAINT user_invite_entity_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'QUOTA_USER'::character varying])::text[])))
);

CREATE TABLE public.user_invite_mc_router_domains (
    user_invite_uuid character varying(255) NOT NULL,
    domain character varying(255)
);

CREATE TABLE public.user_mc_router_domains (
    user_uuid character varying(255) NOT NULL,
    domain character varying(255)
);

CREATE TABLE public.volume_mount_configuration (
    uuid character varying(255) NOT NULL,
    container_path character varying(255) NOT NULL,
    game_server_configuration_uuid character varying(255)
);

CREATE TABLE public.webhook_entity (
    uuid character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    webhook_type character varying(255) NOT NULL,
    webhook_url character varying(255) NOT NULL,
    game_server_uuid character varying(255),
    CONSTRAINT webhook_entity_webhook_type_check CHECK (((webhook_type)::text = ANY ((ARRAY['DISCORD'::character varying, 'SLACK'::character varying, 'N8N'::character varying])::text[])))
);

ALTER TABLE ONLY public.cosy_instance_settings_entity
    ADD CONSTRAINT cosy_instance_settings_entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dummy_instantiated_entity
    ADD CONSTRAINT dummy_instantiated_entity_pkey PRIMARY KEY (value_key);

ALTER TABLE ONLY public.footer_entity
    ADD CONSTRAINT footer_entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.game_entity
    ADD CONSTRAINT game_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.game_server_access_group_entity
    ADD CONSTRAINT game_server_access_group_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.game_server_annotations
    ADD CONSTRAINT game_server_annotations_pkey PRIMARY KEY (game_server_configuration_uuid, annotation_key);

ALTER TABLE ONLY public.game_server_entity
    ADD CONSTRAINT game_server_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.host_volume_mount_configuration
    ADD CONSTRAINT host_volume_mount_configuration_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.layout
    ADD CONSTRAINT layout_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.metric_layout
    ADD CONSTRAINT metric_layout_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.private_dashboard_layout
    ADD CONSTRAINT private_dashboard_layout_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.public_dashboard_layout
    ADD CONSTRAINT public_dashboard_layout_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.public_dashboard
    ADD CONSTRAINT public_dashboard_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.template_entity
    ADD CONSTRAINT template_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT uk2jsk4eakd0rmvybo409wgwxuw UNIQUE (username);

ALTER TABLE ONLY public.user_invite_entity
    ADD CONSTRAINT uk7lklavo5dh9vcf68e2ttmp5xa UNIQUE (secret_key);

ALTER TABLE ONLY public.game_server_entity
    ADD CONSTRAINT uksupgnufxah3g8g7nl3gv5hiu2 UNIQUE (public_dashboard_uuid);

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.user_invite_entity
    ADD CONSTRAINT user_invite_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.volume_mount_configuration
    ADD CONSTRAINT volume_mount_configuration_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.webhook_entity
    ADD CONSTRAINT webhook_entity_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.user_allowed_ports
    ADD CONSTRAINT fk1es51c1enmbq8742o8ear58uh FOREIGN KEY (user_uuid) REFERENCES public.user_entity(uuid);

ALTER TABLE ONLY public.user_invite_allowed_ports
    ADD CONSTRAINT fk264mmfluc8qv7n64l3w4pmky8 FOREIGN KEY (user_invite_uuid) REFERENCES public.user_invite_entity(uuid);

ALTER TABLE ONLY public.private_dashboard_layout
    ADD CONSTRAINT fk2l7imv821u86q673vtk9ahhj0 FOREIGN KEY (private_dashboard_layout_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.docker_execution_command
    ADD CONSTRAINT fk2u4oy0uufuhd8uj43t4t967tt FOREIGN KEY (game_server_configuration_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.public_dashboard_layout
    ADD CONSTRAINT fk5yc0mbgf7qpteld72wjum0par FOREIGN KEY (public_dashboard_uuid) REFERENCES public.public_dashboard(uuid);

ALTER TABLE ONLY public.user_invite_mc_router_domains
    ADD CONSTRAINT fk66bmw4p0hs44mgvaic5i26j4p FOREIGN KEY (user_invite_uuid) REFERENCES public.user_invite_entity(uuid);

ALTER TABLE ONLY public.webhook_entity
    ADD CONSTRAINT fk6t87544aeh0dibdnpsb66chbf FOREIGN KEY (game_server_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.environment_variables
    ADD CONSTRAINT fk6x8n7iofu5oy0g9amkrgigkxc FOREIGN KEY (game_server_configuration_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.private_dashboard_content
    ADD CONSTRAINT fk9b729l0lo6nd52d1a8xpn09es FOREIGN KEY (private_dashboard_layout_id) REFERENCES public.private_dashboard_layout(uuid);

ALTER TABLE ONLY public.public_dashboard_content
    ADD CONSTRAINT fkabso4xusnexapksjuxlmr06h4 FOREIGN KEY (public_dashboard_layout_id) REFERENCES public.public_dashboard_layout(uuid);

ALTER TABLE ONLY public.mc_router_domains
    ADD CONSTRAINT fkc4xvbwurvsk9pkpx4kiq1xysx FOREIGN KEY (cosy_instance_settings_id) REFERENCES public.cosy_instance_settings_entity(id);

ALTER TABLE ONLY public.volume_mount_configuration
    ADD CONSTRAINT fkd7axmtnerkdncmy032p6451j3 FOREIGN KEY (game_server_configuration_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.game_server_annotations
    ADD CONSTRAINT fkdc7uflgrhonfru27vqns52dj5 FOREIGN KEY (game_server_configuration_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.game_server_entity
    ADD CONSTRAINT fkft40jbrvuc1tfsjp2mvbon4d0 FOREIGN KEY (public_dashboard_uuid) REFERENCES public.public_dashboard(uuid);

ALTER TABLE ONLY public.host_volume_mount_configuration
    ADD CONSTRAINT fkhcubhgojns47b3funm80gfaqv FOREIGN KEY (game_server_configuration_host_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.user_mc_router_domains
    ADD CONSTRAINT fkj6mwkqoobjduomxlvhnngkquy FOREIGN KEY (user_uuid) REFERENCES public.user_entity(uuid);

ALTER TABLE ONLY public.port_mappings
    ADD CONSTRAINT fkjevi30f7o07souhaswtavs3th FOREIGN KEY (game_server_configuration_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.game_server_access_group_entity_permissions
    ADD CONSTRAINT fkld8tvlld53se91qkkvnw7a7r0 FOREIGN KEY (game_server_access_group_entity_uuid) REFERENCES public.game_server_access_group_entity(uuid);

ALTER TABLE ONLY public.game_server_entity
    ADD CONSTRAINT fkmae56fdug2vdifsr8d4l11n7u FOREIGN KEY (game_uuid) REFERENCES public.game_entity(uuid);

ALTER TABLE ONLY public.game_server_webhook_events
    ADD CONSTRAINT fkmhi6jwp7nmy7mch677rypcfxo FOREIGN KEY (webhook_id) REFERENCES public.webhook_entity(uuid);

ALTER TABLE ONLY public.game_server_entity
    ADD CONSTRAINT fkmnvaqoegf966fhxsuqmhbapg4 FOREIGN KEY (owner_uuid) REFERENCES public.user_entity(uuid);

ALTER TABLE ONLY public.metric_layout
    ADD CONSTRAINT fknoqrpeujn8987wd7khxwdeg93 FOREIGN KEY (uuid) REFERENCES public.layout(uuid);

ALTER TABLE ONLY public.access_group_users
    ADD CONSTRAINT fknr5978sa0fh4puvsryqeud0os FOREIGN KEY (user_id) REFERENCES public.user_entity(uuid);

ALTER TABLE ONLY public.public_dashboard_layout
    ADD CONSTRAINT fkoxporg1d78yd2v1i444ubl21n FOREIGN KEY (uuid) REFERENCES public.layout(uuid);

ALTER TABLE ONLY public.mc_router_server_domains
    ADD CONSTRAINT fkp4t36lyb5wx3h0vkmkga85cgb FOREIGN KEY (game_server_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.private_dashboard_layout
    ADD CONSTRAINT fkr2b5x5gm6cpdhx0clqnt05jdy FOREIGN KEY (uuid) REFERENCES public.layout(uuid);

ALTER TABLE ONLY public.game_server_access_group_entity
    ADD CONSTRAINT fkrcm40u5oyjnx7mn8ur2kgadkf FOREIGN KEY (game_server_id) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.user_invite_entity
    ADD CONSTRAINT fkrun7dbwme4tn212tu9pdhbvp7 FOREIGN KEY (invited_by_id) REFERENCES public.user_entity(uuid);

ALTER TABLE ONLY public.metric_layout
    ADD CONSTRAINT fktevfojua828rcu178cbhwb7fr FOREIGN KEY (metric_layout_uuid) REFERENCES public.game_server_entity(uuid);

ALTER TABLE ONLY public.access_group_users
    ADD CONSTRAINT fktgmrr37oa9oxnaa9lepdjbarb FOREIGN KEY (access_group_id) REFERENCES public.game_server_access_group_entity(uuid);
